# Generated by Django 5.1.1 on 2024-09-08 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter the subject of your Academic Request', max_length=100)),
                ('body', models.TextField(help_text='Enter the description of your Academis Request', max_length=2000)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the request was made')),
                ('reply', models.TextField(default='No response yet...', help_text='Enter a response to the Academic Request Above', max_length=2000)),
                ('receiver', models.ForeignKey(help_text='Sending to...', on_delete=django.db.models.deletion.CASCADE, related_name='received_academic_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=None, help_text='Sent By...', on_delete=django.db.models.deletion.CASCADE, related_name='sent_academic_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter the subject of your Administrative Request', max_length=100)),
                ('body', models.TextField(help_text='Enter the description of your Administrative Request', max_length=2000)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the request was made')),
                ('reply', models.TextField(default='No response yet...', help_text='Enter a response to the Administrative Request Above', max_length=2000)),
                ('receiver', models.ForeignKey(help_text='Sending to...', on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=None, help_text='Sent By...', on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Administrative Requests',
            },
        ),
    ]
